---
local:
  username: "{{ lookup('ansible.builtin.env', 'USER') }}"
  home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
git:
  username: fntyler
  email: "71953103+fntyler@users.noreply.github.com"
i3wm:
  sur5r:
    signing_key: "https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2024.03.04_all.deb"
    sha256: "f9bb4340b5ce0ded29b7e014ee9ce788006e9bbfe31e96c09b2118ab91fca734"
omb:
  theme: font
  download:
    url: "https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh"
  custom:
    aliases:
      dir: "$HOME/.oh-my-bash/custom/aliases"
      path: "$HOME/.oh-my-bash/custom/aliases/fnt.aliases.sh"
xdg:
  file: "$HOME/.config/user-dirs.dirs"
  download:
    name: "DOWNLOAD"
    path: "$HOME/downloads"
  documents:
    name: "DOCUMENTS"
    path: "$HOME/documents"
  pictures:
    name: "PICTURES"
    path: "$HOME/pictures"
  videos:
    name: "VIDEOS"
    path: "$HOME/videos"
