---
local:
  username: "{{ lookup('ansible.builtin.env', 'USER') }}"
  home: "{{ lookup('ansible.builtin.env', 'HOME') }}"

git:
  username: fntyler
  email: "71953103+fntyler@users.noreply.github.com"

i3wm:
  sur5r:
    signing_key: "https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2024.03.04_all.deb"
    sha256: "f9bb4340b5ce0ded29b7e014ee9ce788006e9bbfe31e96c09b2118ab91fca734"
omb:
  theme: font
  download:
    url: "https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh"
  custom:
    aliases:
      dir: "$HOME/.oh-my-bash/custom/aliases"
      path: "$HOME/.oh-my-bash/custom/aliases/fnt.aliases.sh"

xdg:
  file: "$HOME/.config/user-dirs.dirs"
  download:
    name: "DOWNLOAD"
    path: "$HOME/downloads"
  documents:
    name: "DOCUMENTS"
    path: "$HOME/documents"
  pictures:
    name: "PICTURES"
    path: "$HOME/pictures"
  videos:
    name: "VIDEOS"
    path: "$HOME/videos"

go:
  download:
    url: "https://go.dev/dl/go1.22.4.linux-amd64.tar.gz"
    sha256: "ba79d4526102575196273416239cca418a651e049c2b099f3159db85e7bade7d"

elixir:
  package_manager:
    repo: "https://github.com/asdf-vm/asdf.git"
    version: "v0.14.0"

ripgrep:
  download:
    url: "https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep_14.1.0-1_amd64.deb"
    release: "ripgrep_14.1.0-1_amd64.deb"
    sha256: "78953d5a1c97cb363de0098ff73a7ef33fcae014abd4d62f0da490fe3f58ee94"

rofi:
  download:
    url: "https://github.com/davatorium/rofi/releases/download/1.7.5/rofi-1.7.5.tar.gz"
    release: "rofi-1.7.5.tar.gz"
    sha256: "2fa9a8959e09116e0d4ad4314e4b1904a96ccce51ed6d5a7ef533af3364b9651"
