---
- hosts: localhost
  name: base
  tasks:

    - name: base Include vars
      ansible.builtin.include_vars:
        file: vars/base.yml
      tags: always

    - name: base Install packages
      become: true
      ansible.builtin.apt:
        package:
          - git

    - name: base Git config user name
      become_user: "{{ local.username }}"
      community.general.git_config:
        name: user.name
        scope: global
        value: "{{ git.username }}"

    - name: base Install base packages
      become: true
      ansible.builtin.apt:
        package:
          - docker
          - docker-compose
          - python3-pip

    - name: base Ensure "docker" group exists
      become: true
      ansible.builtin.group:
        name: docker
        state: present

    - name: base Add user to docker group
      become: true
      ansible.builtin.user:
        name: "{{ local.username }}"
        groups: docker
        append: true

    - name: base Stop and disable docker systemd service
      become: true
      ansible.builtin.systemd_service:
        name: docker
        enabled: false
        state: stopped

    - name: base Home tmp dir
      become: true
      ansible.builtin.file:
        path: "{{ local.home }}/tmp"
        owner: "{{ local.username }}"
        group: "{{ local.username }}"
        mode: '0755'
        state: directory

    - name: base Install common packages
      become: true
      ansible.builtin.apt:
        package:
          - fzf
          - jq
          - xclip
          - curl
          - blueman

    - name: base Create dev dir
      become: true
      ansible.builtin.file:
        path: "{{ local.home }}/dev"
        owner: "{{ local.username }}"
        group: "{{ local.username }}"
        mode: '0775'
        state: directory
