---
- hosts: localhost
  name: gitconfig
  tasks:

    - name: gitconfig loop
      community.general.git_config:
        name: remote.origin.url
        scope: local
        value: "git@github.com:fntyler/{{ item }}.git"
        repo: "~/.config/{{ item }}"
      loop:
        - dot-i3
        - dot-nvim
        - dot-tmux
