---
- hosts: localhost
  name: i3wm+i3blocks
  tasks:

    - name: i3wm Download (v4.23)
      ansible.builtin.get_url:
        url: "{{ i3wm.sur5r.signing_key }}"
        dest: "{{ local.home }}/tmp/i3wm_keyring.deb"
        checksum: "sha256:{{ i3wm.sur5r.sha256 }}"

    - name: i3wm Install deb
      become: true
      ansible.builtin.apt:
        deb: "{{ local.home }}/tmp/i3wm_keyring.deb"

    - name: i3wm Add apt repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe"
        state: present
        filename: sur5r-i3wm.list

    - name: i3wm Install pkg
      become: true
      ansible.builtin.apt:
        package: i3
        update_cache: true

    - name: i3wm tack tack version
      ansible.builtin.shell: $(which i3) --version
      register: i3wm_version_result

    - name: i3wm stdout
      ansible.builtin.debug:
        msg: |
          "{{ i3wm_version_result.stdout }}"
      when: i3wm_version_result is defined

    - name: i3blocks Git fetch (latest)
      ansible.builtin.git:
        repo: https://github.com/vivien/i3blocks.git
        dest: "{{ local.home }}/.config/i3blocks"
        depth: 1

    - name: i3blocks Install pkg dependencies
      become: true
      ansible.builtin.apt:
        package:
          - autoconf
          - pkg-config

    - name: i3blocks Setup autogen.sh
      ansible.builtin.command: ./autogen.sh
      args:
        chdir: "{{ local.home }}/.config/i3blocks"

    - name: i3blocks configure
      become: true
      ansible.builtin.command: ./configure
      args:
        chdir: "{{ local.home }}/.config/i3blocks"

    - name: i3blocks Make install
      become: true
      community.general.make:
        chdir: "{{ local.home }}/.config/i3blocks"
        target: install
