---
- hosts: localhost
  name: Zig
  tasks:

    - name: Base include vars
      ansible.builtin.include_vars:
        file: vars/base.yml
      tags: always

    - name: Zig download (0.13.0)
      ansible.builtin.get_url:
        url: "{{ zig.download.url }}"
        dest: "{{ local.home }}/tmp/{{ zig.download.release }}"
        checksum: "sha256:{{ zig.download.sha256 }}"

    - name: Zig extract archive
      become: true
      ansible.builtin.unarchive:
        src: "{{ local.home }}/tmp/{{ zig.download.release }}"
        dest: "/usr/local/"
      register: zig_extraction

    - name: Zig add to system-wide path
      become: true
      ansible.builtin.copy:
        dest: /etc/profile.d/zig.sh
        content: "PATH=$PATH:{{ zig_extraction.dest }}zig-linux-x86_64-{{ zig.release }}/zig"

    - name: Zig collect version
      ansible.builtin.shell: "{{ zig_extraction.dest }}zig-linux-x86_64-{{ zig.release }}/zig version"
      register: zig_version_check

    - name: Zig print version
      ansible.builtin.debug:
        msg: |
          "{{ zig_version_check.stdout }}"
      when: zig_version_check is defined

